name: C++ Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Install dependencies
      run: sudo apt-get install -y g++ cmake

    - name: "Create build directory and run CMake"
      run: |
        mkdir build
        cmake -S . -B build

    - name: "run Tests" 
      run: cmake --build build/ --target coverage
